apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: fact-service
build:
  artifacts:
    - image: fact-service-skaffold
      #buildpacks: {}
      jib: { }
  local:
    push: false
manifests:
  rawYaml:
    - k8s/*.yaml
portForward:
  - resourceType: service
    resourceName: fact-service
    port: 8080
