apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: fact-service
build:
  artifacts:
    - image: europe-north1-docker.pkg.dev/home-lab-k8s/fact-service/fact-service-skaffold
      jib:
        project: org.skillsmapper:fact-service
manifests:
  rawYaml:
    - k8s/*.yaml
portForward:
  - resourceType: service
    resourceName: fact-service
    port: 8080
