apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fact-service-tekton-pipeline
spec:
  project: skillsmapper
  source:
    repoURL: https://github.com/danielvaughan/skillsmapper-for-video.git
    targetRevision: main
    path: .argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: tekton-pipelines
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
